name: .NET CI - Build and Test

on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    branches:
      - "main"
      - "develop"

env:
  DOTNET_VERSION : '9.0'
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      # Шаг 1: Получить код из репозитория
      - name: Checkout Repo
        uses: actions/checkout@v4 # Это checkout -- это actions самого GitHub
        # все actions хранятся в одноименной директории
      # Шаг 2: Установить .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.DOTNET_VERSION}} # Тут используем переменную
      
      # Шаг 3: Восстановить все зависимости
      - name: Restore deps
        run: dotnet restore # Это уже не готовый actions
          # Поэтому пишем вызываемую команду
      
      # Шаг 4: Собираем проект
      - name: Build Solution
        run: dotnet build --no-restore --configuration Release
      
      # Шаг 5: Выполняем модульное тестирование  
      - name: Run unit tests
        run: dotnet test --configuration Release

